version: 0.{build}
skip_tags: true
image: Visual Studio 2019
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: project_files/iv-screen-patch.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: >-     
    
    cd "c:\projects\iv-screen-patch\output\asi\"
                      
    7z a iv-screen-patch.zip IVScreenPatch.asi

    Get-ChildItem .\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
